# Generated by Django 5.1.6 on 2025-03-16 03:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='受体名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('height', models.FloatField(verbose_name='高度（米）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '受体',
                'verbose_name_plural': '受体管理',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('xmn', models.FloatField(verbose_name='最小经度')),
                ('xmx', models.FloatField(verbose_name='最大经度')),
                ('ymn', models.FloatField(verbose_name='最小纬度')),
                ('ymx', models.FloatField(verbose_name='最大纬度')),
                ('geojson', models.TextField(verbose_name='区域边界 GeoJSON')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域管理',
            },
        ),
        migrations.CreateModel(
            name='ModelGFSStilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='删除标记', verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='letters_only', message='只允许使用大小写英文字母', regex='^[a-zA-Z]+$')], verbose_name='模型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('receptor', models.ManyToManyField(related_name='model_gfs_stilts', to='model_gfs_stilt.receptor', verbose_name='受体')),
            ],
            options={
                'verbose_name': 'GFS-STILT模型',
                'verbose_name_plural': 'GFS-STILT模型管理',
            },
        ),
        migrations.AddField(
            model_name='receptor',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptors', to='model_gfs_stilt.region', verbose_name='所属区域'),
        ),
    ]
