# Generated by Django 5.1.6 on 2025-03-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_gfs_stilt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelgfsstilt',
            table='model_gfs_stilt_config',
        ),
    ]
