# Generated by Django 5.1.6 on 2025-03-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_gfs_stilt', '0002_alter_modelgfsstilt_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgfsstilt',
            name='xres',
            field=models.FloatField(default=0.001, verbose_name='X方向分辨率'),
        ),
        migrations.AddField(
            model_name='modelgfsstilt',
            name='yres',
            field=models.FloatField(default=0.001, verbose_name='Y方向分辨率'),
        ),
    ]
