# Generated by Django 5.1.6 on 2025-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_gfs_stilt', '0003_modelgfsstilt_xres_modelgfsstilt_yres'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgfsstilt',
            name='n_cores',
            field=models.IntegerField(default=4, verbose_name='计算核心数'),
        ),
    ]
