# Generated by Django 5.1.6 on 2025-03-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_gfs_stilt', '0004_modelgfsstilt_n_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgfsstilt',
            name='gfs_file_retention_days',
            field=models.IntegerField(default=3, verbose_name='GFS文件保留天数'),
        ),
    ]
