# Generated by Django 5.1.6 on 2025-04-06 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_gfs_stilt', '0005_modelgfsstilt_gfs_file_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutantSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='污染源名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='描述信息', null=True)),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('source_type', models.CharField(help_text='污染源类型', max_length=50)),
                ('emission_rate', models.FloatField(help_text='排放率')),
            ],
            options={
                'verbose_name': '污染源',
                'verbose_name_plural': '污染源管理',
                'db_table': 'g_pollutant_source',
            },
        ),
        migrations.AlterField(
            model_name='modelgfsstilt',
            name='gfs_file_retention_days',
            field=models.IntegerField(default=365, verbose_name='GFS文件保留天数'),
        ),
        migrations.AlterField(
            model_name='modelgfsstilt',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='modelgfsstilt',
            name='n_cores',
            field=models.IntegerField(default=8, verbose_name='计算核心数'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='height',
            field=models.IntegerField(verbose_name='高度（米）'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geojson',
            field=models.TextField(blank=True, null=True, verbose_name='区域边界 GeoJSON'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除'),
        ),
        migrations.AlterModelTable(
            name='modelgfsstilt',
            table='g_model_config',
        ),
        migrations.AlterModelTable(
            name='receptor',
            table='g_receptor',
        ),
        migrations.AlterModelTable(
            name='region',
            table='g_region',
        ),
    ]
